### ISSUE TITLE
need some fix for Safari

### ISSUE THREAD

**Issue by hfu** [frogcat/csmap#1]
Confirmed to work with Chrome and Firefox. Maybe technical difficulty with Safari.
https://twitter.com/_hfu_/status/812099760463040512

**Comment by frogcat** [comment]
CSMap depends on window.fetch, but current version of Safari does not support fetch.
<http://caniuse.com/#search=fetch>

As a quick fix, I added window.fetch polyfill. 
Unfortunately, I don't have any Sarfari installed device, so please let me know if it works well.

**Comment by frogcat** [comment]
Fixed.
dem-curvature-slope-layer.js is added to solve performance and platform problems, and old unnecessary implementations are removed. XHR is used insted of fetch.
8802a473e1498a72eb1a2220dd665eb4a979f4ed

Tested with

- Chrome (windows7 64bit)
- Firefox (windows7 64bit)
- IE11 (windows7 64bit)
- Chrome (Android 4.4.2)
- Safari (iOS 10)

**Comment by hfu** [comment]
Nice! It works very well with Safari. Excuse me for a late response.
